### PR TITLE
fix/solidart-benchmark

### PR DESCRIPTION
**Pull request by nank1ro**
## Description

Hi there, I'm the creator of [solidart](https://github.com/nank1ro/solidart/)
I saw your benchmark on [X](https://x.com/1kap10/status/1740867275790684358?s=20) and I wanted to understand what the problems were with solidart.
I found that you ran the benchmarks not in release mode, added the release mode to the launch.json.
In debug mode solidart does some heavy computation for the devtools extension, I added the `SolidartConfig.devToolsEnabled = false` line to disable the devtools even in debug mode.
Despite this change, I believe it is always good to benchmark in release mode.

In addition I saw that you used a `Solid` to provide the signals. The `Solid` widget is an InheritedWidget and using it was not necessary for the example. It does some computations that are a bit slower just because it tries to find the InheritedWidget every time the value changes.
```diff
- Solid(
-     providers: [
-         Provider<Signal<double>>(
-             create: () => solidartObservable.observable,
-          ),
-        ],
-       builder: (ctx) {
+         SignalBuilder(
+            signal: solidartObservable.observable,
+            builder: (_, val, __) {
               final startingLeftOffset = (screenWidth - totalRowWidth) / 2;
               final row = i ~/ columns;
               final col = i % columns;
-              final val = ctx.observe<double>();
```
In any case, I will personally see if I can improve the performance of the `Solid` widget.
Running the benchmark (20k raindrops and a bucket capacity of 30k) in release mode on my machine (MacBook Air M1) I get these results (in order of performance):
| Library                                                 | Raindrops/s | Time to fill bucket |
|---------------------------------------------------------|-------------|---------------------|
| value_LB                                                | 5510        | 5.44s               |
| [mobx](https://pub.dev/packages/flutter_mobx)           | 5172        | 5.8s                |
| [state_beacon](https://pub.dev/packages/state_beacon)   | 5016        | 5.98s               |
| [solidart](https://pub.dev/packages/solidart)           | 5008        | 5.99s               |
| [signals](https://pub.dev/packages/signals)             | 3109        | 9.64s               |
| stream_builder                                          | 2518        | 11.9s               |
| [context_watch](https://pub.dev/packages/context_watch) | 2377        | 12.6s               |

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by zupat** [comment]
Hey, thanks for the PR.

I did in fact run in the release mode as I built the app(which defaults to release mode) so I can relaunch it quickly after each test. I will merge this but note that using `SignalBuilder` is not totally fair as the other libs can watch muliple observables at the same time. So it would fall in the same category as VLB and StreamBuilder which can only watch a single obs. I also intended to add a color signal that changes overtime so I'm not sure how that would work...maybe I should nest the SignalBuilders ? not sure how this would affect performance.

edit:
I see that there's a `DualSignalBuilder` so that should solve the issue.

**Comment by zupat** [comment]
I updated the results table.

**Comment by nank1ro** [comment]
I did not understand this sentence
> note that using `SignalBuilder` is not totally fair as the other libs can watch multiple observables at the same time. So it would fall in the same category as VLB and StreamBuilder which can only watch a single obs

I take mobx as an example:
```dart
for (int i = 0; i < rainDropCount.peek(); i++)
  fmx.Observer(
    builder: (ctx) {
      final startingLeftOffset = (screenWidth - totalRowWidth) / 2;
      final row = i ~/ columns;
      final col = i % columns;
      final val = mobxObservable.observable.value;
      return Positioned(
        left: startingLeftOffset + col * (dropWidth + dropSpacing),
        top: initialTopOffset +
            row * dropSpacing +
            200.0 * (1 + (val * .1)),
        child: const Icon(
          Icons.water_drop,
          size: dropWidth,
          color: Colors.blue,
        ),
      );
    },
  ),
```
There is an `fmx.Observer` that tracks just one signal per time, which is `mobxObservable.observable.value`.
This is equivalent to the `SignalBuilder` implementation:
```dart
for (int i = 0; i < rainDropCount.peek(); i++)
  SignalBuilder(
    signal: solidartObservable.observable,
    builder: (_, val, __) {
      final startingLeftOffset = (screenWidth - totalRowWidth) / 2;
      final row = i ~/ columns;
      final col = i % columns;
      return Positioned(
        left: startingLeftOffset + col * (dropWidth + dropSpacing),
        top: initialTopOffset +
            row * dropSpacing +
            200.0 * (1 + (val * .1)),
        child: const Icon(
          Icons.water_drop,
          size: dropWidth,
          color: Colors.blue,
        ),
      );
    },
  ),
```

**Comment by zupat** [comment]
I meant the other libs _can_ watch an unlimited number of signals while you have to specify which signals you want to watch with `Solid`. 

In the `mobx` example. it has to look up which signals were used in its build function while the `Solid` widgets gets "told" which signals it should watch.

**Comment by nank1ro** [comment]
So you consider the operation of looking up which signals to track, even for a single signal, more expensive than telling which signal to track, that's right?

**Comment by zupat** [comment]
Well technically it is, but being less expensive is not the issue. I'm just stating that the capabilities aren't equivalent and the UX is not the same.

**Comment by nank1ro** [comment]
But this has nothing to do with the benchmark. The benchmarks of the libraries you put in for me are equivalent because they do the same thing. 
What you wrote in the README
> stream_builder and value_LB are not perfect comparisons as they can only listen to 1 observable at a time... but they serve as a good baseline
solidart implementation uses SolidBuilder which can only listen to a fixed number of observables so it's not a perfect comparison either.

to me has nothing to do with the benchmark itself, but it's your conclusion because you just saw that some features are lacking in some libraries.
To me, the example of the value listenable builder, in terms of benchmarks, is equivalent to all other libraries. If other libraries have more features, it does not mean that they should be slow for that reason. On the contrary, this is a point against the other libraries in terms of performance, because they do heavier computations underneath (This is not necessarily a bad thing, but in terms of performance it has to be taken into account).

**Comment by zupat** [comment]
Ergonomics matters. I think it's good to separate libs that can watch an unlimited number and those that can watch a fixed number of signals.

**Pull request merged**
